name: GamemodePlus
version: 2.0.0
main: dev.goldencodes.gamemodeplus.GameModePlus
api-version: 1.16
authors: [ GoldenCodes ]
description: A new and improved version of GamemodeX
website: https://www.indeedious.site
